New parsing (no values after -a -b -c)

diff --git a/xtf b/xtf
--- a/xtf
+++ b/xtf
@@ -27,6 +27,11 @@ ab_set_error(){
     usage 1
 }
 
+two_names_set_error(){
+    echo "Error: Two names set" >&2
+    usage 1
+}
+
 user=''
 command=""
 a_flag=false
@@ -34,16 +39,13 @@ b_flag=false
 c_flag=false
 
 
-args=( "$@" ) #save all arguments in array
+#args=( "$@" ) #save all arguments in array
 # da sa vynechat, pouzivat vzdy len $1 a shiftovat
 
-for i in "${!args[@]}"; do #iterate through the whole array
-    echo "${args[i]}"
+while [[ -n $1 ]]; do #iterate through the whole array
+    echo "$1"
 
-    case "${args[i]}" in #switch
-        '')
-            continue
-            ;;
+    case "$1" in #switch
         -h|--help)
             usage 0
             ;;
@@ -63,55 +65,26 @@ for i in "${!args[@]}"; do #iterate through the whole array
             c_flag=true
             ;; #expect value
         list|list-currency|status|profit)
-           command="${args[i]}"
+           command="$1"
            ;;
         *)
-            if [[ -z $user ]]; then
-            
-                user="${args[i]}"
+            if [ ! -f "$1" ]; then
+                if [ -z "$user" ]; then
+                    user="$1"
+                else 
+                    two_names_set_error
+                fi
+
             fi
             # -f filename - validacia ci subor je subor
     esac
-    unset "args[i]"
+    shift
 done
 
-#optstring=":ha:b:c:"
-
-#while getopts "$optstring" opt; do
- #   case $opt in
- #       h) usage ;;
- #       a) a_flag=true ;;
- #       b) b_flag=true ;;
- #       c) c_flag=true ;;
- #       ?)
- #           echo "Invalid option: -$opt" >&2
- #           usage ;;
- #   esac
-#done
-#shift $((OPTIND - 1))  # Shift the processed options
-
-# Check for command
-#if [ -n "$1" ]; then
-#    command="$1"
-#    shift  # Move to next argument
-#else
-#    echo "Error: Command not specified." >&2
-#    usage
-#fi
-
-# Process the command
-#case $command in
-#    list) echo "Executing list command" ;;
-#    list-currency) echo "Executing list-currency command" ;;
-#    status) echo "Executing status command" ;;
-#    profit) echo "Executing profit command" ;;
-#    *) echo "Invalid command: $command" >&2
-#       usage ;;
-#esac
 
 echo ""
-echo "$command"
-echo "$a_flag"
-echo "$b_flag"
-echo "$c_flag"
-echo "$user"
+echo "command: $command"
+echo "a: $a_flag"
+echo "b: $b_flag"
+echo "c: $c_flag"
+echo "user: $user"
